name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: setting an error messagez
              run: echo "::error::Missing Semicolon"

            - name: Setting an error message with parameter
              run: echo "::error title:Error title,file=app.js,
              line=2, endLine=3, col=5, endColumn=7::Missing Semicolon"

            - name: Setting an Debug message with parameter
              run: echo "::debug title:Debug title, file=app.js, 
              line=2, endLine=3, col=5, endColumn=7::Missing Semicolon"

            - name: Setting an Worning message with parameter
              run: echo "::warning title:Warning title, file=app.js, 
              line=2, endLine=3, col=5, endColumn=7::Missing Semicolon"

            - name: Setting an Notice message with parameter
              run: echo "::notice title:Notice title, file=app.js, 
              line=2, endLine=3, col=5, endColumn=7::Missing Semicolon"

