name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: setting an error messagez
              run: echo "::error::Missing Semicolon"
              